version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_scheduler
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  scheduler:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  db_data:
